SELECT 
    COLUMN_NAME, 
    COLUMNPROPERTY(OBJECT_ID('[FNLAccount].[dbo].Member'), COLUMN_NAME, 'IsIdentity') AS IsIdentity
FROM 
    INFORMATION_SCHEMA.COLUMNS 
WHERE 
    TABLE_NAME = 'Member'
    AND COLUMN_NAME = 'mUserNo';